# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GtfsShapesCreator
                                 A QGIS plugin
 Generates GTFS shapes.txt files by routing transit lines on OpenStreetMap road and rail networks, with current support for opentransportdata.swiss
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-15
        copyright            : (C) 2025 by Luigi Dal Bosco
        email                : luigi.dalbosco@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GtfsShapesCreator class from file GtfsShapesCreator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gtfs_shapes_creator import GtfsShapesCreator
    return GtfsShapesCreator(iface)
