# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GTFSagencySelect
                                 A QGIS plugin
 You can choose one or more public transport agencies for routing them in OSM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-12-03
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Luigi
        email                : luigi.dalbosco@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
# from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
# from qgis.PyQt.QtGui import QIcon
# from qgis.PyQt.QtWidgets import QAction, QListWidgetItem
# from PyQt5.QtCore import Qt
# from PyQt5.QtWidgets import QMessageBox

# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the dialog

import os.path

import pandas as pd
from collections import defaultdict
import os

# import webbrowser
# import glob
# import zipfile
# import time
from pathlib import Path
import datetime

# will be set False in run()
# self.first_start = True

# self.GTFSagency_selection_dialog.SwissLink_for_the_Download.clicked.connect(self.__goToSwissLink)

# self.GTFSagency_selection_dialog.LookFor_the_GTFS_Zips.clicked.connect(self.__lookForZips)

# self.GTFSagency_selection_dialog.UnzipButton.clicked.connect(self.__unzipFile)

# self.GTFSagency_selection_dialog.updateAgenciesButton.clicked.connect(self.__updateAgences)


def update_agences(gtfs_folder_path):
    agency = pd.read_csv(str(gtfs_folder_path) + "/agency.txt", dtype="str")
    agency["id_name"] = (
        agency["agency_id"].astype(str).fillna("")
        + " - "
        + agency["agency_name"].astype(str).fillna("")
    )

    agency = agency.sort_values(by="agency_name")
    ls_agency = agency.id_name.unique()
    return ls_agency


def check_gtfs_folder(gtfs_folder_path):
    ls_gtfs_files = [
        "agency.txt",
        "routes.txt",
        "trips.txt",
        "stops.txt",
        "stop_times.txt",
    ]
    ls_missing = []
    for file in ls_gtfs_files:
        file_path = os.path.join(gtfs_folder_path, file)
        if not os.path.exists(file_path):
            ls_missing.append(file)
    if len(ls_missing) > 0:
        if len(ls_missing) == len(ls_gtfs_files):
            raise TypeError(
                "It's not the GTFS folder, make sure you unziped the GTFS file"
            )
        else:
            raise TypeError(
                f"Something wrong with your GTFS folder {ls_missing} are missing! in the {gtfs_folder_path}"
            )

    # def unload(self):
    #     """Removes the plugin menu item and icon from QGIS GUI."""
    #     for action in self.actions:
    #         self.iface.removePluginMenu(
    #             self.tr(u'&GTFS agency selection'),
    #             action)
    #         self.iface.removeToolBarIcon(action)

    # def run(self):
    #     """Run method that performs all the real work"""

    #     # Create the dialog with elements (after translation) and keep reference
    #     # Only create GUI ONCE in callback, so that it will only load when the plugin is started
    #     if self.first_start == True:
    #         self.first_start = False

    #     # show the dialog
    #     self.GTFSagency_selection_dialog.show()
    #     # Run the dialog event loop
    #     result = self.GTFSagency_selection_dialog.exec_()
    #     # See if OK was pressed

    #     dwnldfld = self.GTFSagency_selection_dialog.downloadDirFileWidget.filePath()

    #     selected_items = self.GTFSagency_selection_dialog.listAgenciesWidget.selectedItems()

    #     if result:
    #         # Do something useful here - delete the line containing pass and
    #         # substitute with your code.
    #         msg = QMessageBox()
    #         msg.setIcon(QMessageBox.Information)
    #         # setting message for Message Box
    #         msg.setText("The \'Agency selection\' is in progress wait until the message box is closed")
    #         # setting Message box window title
    #         msg.setWindowTitle("!! wait the next message \'GTFS agency selection\' is in progress !!")
    #         msg.show()


def load_csv_in_dfs(
    GTFSnm_angledf_csv,
    OSMwithGTFS_csv,
    dfnomatch_csv,
    GTFSnm_rect_csv,
    GTFSnmRCT_posdf_csv,
):
    if os.path.exists(GTFSnm_angledf_csv):
        GTFSnm_angledf = pd.read_csv(GTFSnm_angledf_csv)
    if os.path.exists(OSMwithGTFS_csv):
        OSMwithGTFS = pd.read_csv(OSMwithGTFS_csv)
    if os.path.exists(dfnomatch_csv):
        dfnomatch = pd.read_csv(dfnomatch_csv)
    if os.path.exists(GTFSnm_rect_csv):
        GTFSnm_rect = pd.read_csv(GTFSnm_rect_csv)
    if os.path.exists(GTFSnmRCT_posdf_csv):
        GTFSnmRCT_posdf = pd.read_csv(GTFSnmRCT_posdf_csv)
    return (
        GTFSnm_angledf,
        OSMwithGTFS,
        dfnomatch,
        GTFSnm_rect,
        GTFSnmRCT_posdf,
    )


def get_agecy_s_routes(ls_agencies_selected, gtfs_folder_path):

    print("you selected:")
    for agen in ls_agencies_selected:
        print(agen)
    agencies_num = [agen.split(" - ")[0] for agen in ls_agencies_selected]
    agencies_folder = "agen"
    agencies_num = [agen.split(" - ")[0] for agen in ls_agencies_selected]
    for agen in agencies_num:
        agencies_folder = str(agencies_folder) + "_" + str(agen)

    routes_txt = str(gtfs_folder_path) + "/routes.txt"
    routes = pd.read_csv(routes_txt, dtype="str")

    agency_routes = routes[routes.agency_id.isin(agencies_num)]

    return agency_routes, agencies_folder


def generate_agencies_gtfs(gtfs_folder_path, selected_agencies, count_all_agencies):

    ls_agencies_selected = [item.text() for item in selected_agencies]
    if len(selected_agencies) == count_all_agencies:
        agencies_folder = str(Path(gtfs_folder_path))
        gtfs_folder_path = str(Path(gtfs_folder_path).parent.absolute())
    else:
        agen_folder = "agen"
        agencies_num = [agen.split(" - ")[0] for agen in ls_agencies_selected]
        for agen in agencies_num:
            agen_folder = str(agen_folder) + "_" + str(agen)
        agencies_folder = os.path.join(gtfs_folder_path, agen_folder)

        if not os.path.exists(agencies_folder):
            create_agecies_gtfs(agen_folder, agencies_num, gtfs_folder_path)

    outputspath = os.path.join(agencies_folder, "outputs")
    if not os.path.exists(outputspath):
        os.makedirs(outputspath)
    return agencies_folder, outputspath


def create_agecies_gtfs(agen_folder, agencies_num, gtfs_folder_path):

    agency_txt = str(gtfs_folder_path) + "/agency.txt"
    routes_txt = str(gtfs_folder_path) + "/routes.txt"
    trips_txt = str(gtfs_folder_path) + "/trips.txt"
    stop_times_txt = str(gtfs_folder_path) + "/stop_times.txt"
    stops_txt = str(gtfs_folder_path) + "/stops.txt"
    calendar_txt = str(gtfs_folder_path) + "/calendar.txt"
    calendar_dates_txt = str(gtfs_folder_path) + "/calendar_dates.txt"

    agency = pd.read_csv(agency_txt, dtype={"agency_id": "str"})
    routes = pd.read_csv(routes_txt, dtype="str")
    trips = pd.read_csv(trips_txt, dtype="str")
    types = defaultdict(lambda: str, stop_sequence="int")
    stop_times = pd.read_csv(stop_times_txt, dtype=types)
    types = defaultdict(lambda: str, stop_lon="float", stop_lat="float")
    stops = pd.read_csv(stops_txt, dtype=types)
    calendar = pd.read_csv(calendar_txt, dtype="str")
    calendar_dates = pd.read_csv(calendar_dates_txt, dtype="str")

    agency_fld = os.path.join(gtfs_folder_path, agen_folder)

    if not os.path.exists(agency_fld):
        os.makedirs(agency_fld)

    agency_select = pd.DataFrame()

    for agen in agencies_num:
        agencies = agency[agency["agency_id"] == agen]
        agency_select = pd.concat([agency_select, agencies], ignore_index=True)

    agency_select.to_csv(str(agency_fld) + "/agency.txt", index=False)

    agency_routes = routes[routes.agency_id.isin(agencies_num)]
    trnsprt_correspondant = {
        "T": "Tram",
        "B": "Bus",
        "R": "RegRailServ",
        "FUN": "Funicular",
    }
    agency_routes["trnsprt"] = (
        agency_routes["route_desc"].map(trnsprt_correspondant).fillna("trnsprt")
    )
    agency_routes["trnsp_shrt_name"] = (
        agency_routes["trnsprt"].astype(str)
        + "_"
        + agency_routes["route_short_name"].astype(str)
    )
    agency_routes.to_csv(str(agency_fld) + "/routes.txt", index=False)

    ls_routes = agency_routes.route_id.unique()
    trips_agency = trips[trips.route_id.isin(ls_routes)]
    trips_agency.to_csv(str(agency_fld) + "/trips.txt", index=False)

    ls_trips = trips_agency.trip_id.unique()
    agency_stop_times = stop_times[stop_times.trip_id.isin(ls_trips)]
    agency_stop_times.to_csv(str(agency_fld) + "/stop_times.txt", index=False)

    ls_stops = agency_stop_times.stop_id.unique()
    agency_stops = stops[stops.stop_id.isin(ls_stops)]
    agency_stops.to_csv(str(agency_fld) + "/stops.txt", index=False)

    ls_service = trips_agency.service_id.unique()

    agency_calendar = calendar[calendar.service_id.isin(ls_service)]
    agency_calendar.to_csv(str(agency_fld) + "/calendar.txt")

    agency_calendar_dates = calendar_dates[calendar_dates.service_id.isin(ls_service)]
    agency_calendar_dates.to_csv(str(agency_fld) + "/calendar_dates.txt")


#         msg.close()

#         msg2 = QMessageBox()
#         msg2.setIcon(QMessageBox.Information)
#         msg2.setText("The selected agencies were saved \nin the folder: "+str(agency_fld))
#         msg2.setWindowTitle("Done !")
#         msg2.exec_()
