# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GtfsShapesCreatorDockWidget
                                 A QGIS plugin
 Generates GTFS shapes.txt files by routing transit lines on OpenStreetMap road and rail networks, with current support for opentransportdata.swiss
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-15
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Luigi Dal Bosco
        email                : luigi.dalbosco@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from pathlib import Path
from qgis import processing
from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from qgis.core import (
    QgsCoordinateReferenceSystem,
    QgsVectorLayer,
    QgsVectorFileWriter,
    QgsRasterLayer,
    QgsProject,
    QgsFields,
    QgsField,
    QgsPointXY,
    QgsExpression,
    QgsExpressionContext,
    QgsExpressionContextUtils,
    edit,
    QgsRectangle,
)

from .agency_selection import (
    update_agences,
    check_gtfs_folder,
    get_agecy_s_routes,
    create_agecies_gtfs,
)

from .osmimport_routes_ptstops import (
    downloading_ways,
    downloading_railway,
    busroutes,
    full_city_roads,
    Selected_Ttbls,
    preapare_GTFSstops_by_transport,
    time_tables_perTransport,
    angles_tram,
    angles_buses,
    rectangles_sidewalk,
    rectangles_OSMonROADline,
    OSMintersecGTFS,
    OSM_PTstps_dwnld,
    stp_posGTFSnm_rect,
    joinNEWandValidOSM,
    highway_average_speed,
    transcript_main_files,
    Ttbls_plus,
    angle_onRD_sidewalk,
    shape_assignement,
    if_not_make,
    if_display,
    if_remove,
)
from .OSM_PT_routing import if_remove_single_file
from qgis.PyQt.QtWidgets import QListWidgetItem
from PyQt5.QtCore import Qt
import pandas as pd
import json
import datetime

from .resources import *

import webbrowser
from PyQt5.QtCore import QVariant
from qgis.PyQt.QtWidgets import QListWidgetItem

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "gtfs_shapes_creator_dockwidget_base.ui")
)


class GtfsShapesCreatorDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, iface, parent=None):
        """Constructor."""
        super(GtfsShapesCreatorDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect

        self.iface = iface

        self.setupUi(self)

        self.openTheLinkButton.clicked.connect(self.__goToSwissLink)

        self.updateAgenciesButton.clicked.connect(self.__updateAgencies)

        self.searchButton.clicked.connect(self.___searchItem)

        self.updateBusButton.clicked.connect(self.__updateBuses)

        self.uploadOSMButton.clicked.connect(self.__uploadOSM)

        self.zoomStopButton.clicked.connect(self.__ZoomStop)

    #    !!! ---- agency_seleciton functions ---- !!!

    def __goToSwissLink(self):
        webbrowser.open(
            "https://data.opentransportdata.swiss/en/dataset/?q=GTFS&groups=timetables&sort=metadata_modified+desc"
        )

    def __updateAgencies(self):

        self.listAgenciesWidget.clear()  # Clear existing items
        gtfs_folder_path = self.mGtfsFolderWidget.filePath()
        check_gtfs_folder(gtfs_folder_path)
        ls_agencies = update_agences(gtfs_folder_path)
        for agen in ls_agencies:
            self.listAgenciesWidget.addItem(QListWidgetItem(str(agen)))

    def ___searchItem(self):
        search_string = self.searchLineEdit.text()
        match_items = self.listAgenciesWidget.findItems(search_string, Qt.MatchContains)
        for idx in range(self.listAgenciesWidget.count()):
            it = self.listAgenciesWidget.item(idx)
            it.setHidden(it not in match_items)

    def __updateBuses(self):

        selected_items = self.listAgenciesWidget.selectedItems()

        gtfs_folder_path = self.mGtfsFolderWidget.filePath()

        ls_agencies_selected = [item.text() for item in selected_items]
        routes, agency_name_fold = get_agecy_s_routes(
            ls_agencies_selected, gtfs_folder_path
        )

        self.listBusWidget.clear()  # Clear existing items
        trnsprt_correspondant = {
            "T": "Tram",
            "B": "Bus",
            "R": "RegRailServ",
            "FUN": "Funicular",
        }
        routes["trnsprt"] = (
            routes["route_desc"].map(trnsprt_correspondant).fillna("trnsprt")
        )
        routes["trnsp_shrt_name"] = (
            routes["trnsprt"].astype(str) + "_" + routes["route_short_name"].astype(str)
        )
        ls_transport = routes.trnsp_shrt_name.unique()

        files_to_delete_next_bus_loading_json = (
            str(gtfs_folder_path)
            + "/"
            + str(agency_name_fold)
            + "/temp/files_to_delete_next_bus_loading.json"
        )
        if os.path.exists(files_to_delete_next_bus_loading_json):
            with open(files_to_delete_next_bus_loading_json, "r") as f:
                files_to_del = json.load(f)
            for file in files_to_del["path"]:
                files_to_del = if_remove(file, files_to_del)
            files_to_del_str = json.dumps(files_to_del, indent=2)
            with open(files_to_delete_next_bus_loading_json, "w") as f:
                f.write(files_to_del_str)
            if files_to_del["path"]:
                print("the files will be deleted only restarting QGIS")
                print(
                    'RESTART QGIS and click again the "Update Transport numbers" button'
                )
        self.toolBox.setCurrentIndex(1)
        for trnsprt in ls_transport:
            self.listBusWidget.addItem(QListWidgetItem(str(trnsprt)))

        return routes, agency_name_fold

    #    !!! ---- OSMimport_road_PTstops functions ---- !!!
    def __uploadOSM(self):
        selected_items = self.listBusWidget.selectedItems()

        # load the downloads and output folders

        gtfs_folder_path = self.mGtfsFolderWidget.filePath()

        outputspath = "to define"  # to define
        if not os.path.exists(outputspath):
            os.makedirs(outputspath)

        selected_agencies = self.listAgenciesWidget.selectedItems()

        ls_agencies_selected = [item.text() for item in selected_agencies]

        agen_folder = "agen"
        agencies_num = [agen.split(" - ")[0] for agen in ls_agencies_selected]
        for agen in agencies_num:
            agen_folder = str(agen_folder) + "_" + str(agen)

        count_all_agencies = self.listAgenciesWidget.count()
        if len(selected_agencies) == count_all_agencies:
            agencies_folder = str(Path(gtfs_folder_path))
            gtfs_folder_path = str(Path(gtfs_folder_path).parent.absolute())
        else:
            agencies_folder = os.path.join(gtfs_folder_path, agen_folder)

            if not os.path.exists(agencies_folder):
                print(
                    f"at{datetime.datetime.now()} start to prepare the agency GTFS(basic)"
                )
                create_agecies_gtfs(agen_folder, agencies_num, gtfs_folder_path)

        temp_folder = "OSM_data"
        road_temp_folder = os.path.join(agencies_folder, temp_folder)

        trips_txt = str(agencies_folder) + "/trips.txt"

        stops_txt = str(agencies_folder) + "/stops.txt"
        stops = pd.read_csv(stops_txt)

        agency_txt = str(agencies_folder) + "/agency.txt"
        agency = pd.read_csv(agency_txt)
        ls_agency = agency.agency_id.unique()

        lines_df_csv = str(agencies_folder) + "/lines_files_list.csv"

        south = round(float(stops.stop_lat.min()) - 0.05, 6)
        west = round(float(stops.stop_lon.min()) - 0.05, 6)
        north = round(float(stops.stop_lat.max()) + 0.05, 6)
        east = round(float(stops.stop_lon.max()) + 0.05, 6)

        OSM_ways_name = "OSM_ways"
        OSM_ways_gpkg = str(road_temp_folder) + "/" + str(OSM_ways_name) + ".gpkg"

        OSM_tramways_name = "OSM_tramways"
        OSM_tramways_gpkg = (
            str(road_temp_folder) + "/" + str(OSM_tramways_name) + ".gpkg"
        )

        OSM_Regtrainways_name = "OSM_Regtrainways"
        OSM_Regtrainways_gpkg = (
            str(road_temp_folder) + "/" + str(OSM_Regtrainways_name) + ".gpkg"
        )

        OSM_funicularways_name = "OSM_funicularways"
        OSM_funicularways_gpkg = (
            str(road_temp_folder) + "/" + str(OSM_funicularways_name) + ".gpkg"
        )

        extent = str(south) + "," + str(west) + "," + str(north) + "," + str(east)
        extent_quickosm = (
            str(south)
            + ","
            + str(west)
            + ","
            + str(north)
            + ","
            + str(east)
            + " [EPSG:4326]"
        )

        # naming files and paths

        OSM_roads_name = "OSM_roads"
        OSM_roads_gpkg = str(road_temp_folder) + "/" + str(OSM_roads_name) + ".gpkg"

        OSM_tram_name = "OSM_tram"
        OSM_rails_gpkg = str(road_temp_folder) + "/" + str(OSM_tram_name) + ".gpkg"

        OSM_Regtrain_name = "OSM_Regtrain"
        OSM_Regtrain_gpkg = (
            str(road_temp_folder) + "/" + str(OSM_Regtrain_name) + ".gpkg"
        )

        OSM_funicular_name = "OSM_funicular"
        OSM_funicular_gpkg = (
            str(road_temp_folder) + "/" + str(OSM_funicular_name) + ".gpkg"
        )

        OSM_roads_nameCSV = "OSM_roads_CSV"
        OSM_roads_csv = str(road_temp_folder) + "/" + str(OSM_roads_name) + ".csv"

        highway_speed_name = "highway_average_speed"
        highway_speed_csv = (
            str(road_temp_folder) + "/" + str(highway_speed_name) + ".csv"
        )

        bus_lanes_name = "OSM_bus_lanes"
        OSM_bus_lanes_gpkg = str(road_temp_folder) + "/" + str(bus_lanes_name) + ".gpkg"

        full_roads_name = "full_city_roads"
        full_roads_gpgk = str(road_temp_folder) + "/" + str(full_roads_name) + ".gpkg"

        city_roads_name = "city roads"

        city_rails_name = "city rails"

        city_Regtrain_name = "city Regtrain"

        city_funicular_name = "city funicular"

        Ttlbs_txt = str(agencies_folder) + "/stop_times.txt"

        Ttbls_plus_name = "stop_times_plus"
        Ttbls_plus_csv = str(agencies_folder) + "/" + str(Ttbls_plus_name) + ".csv"

        Ttbls_selected_name = "stop_times_selected_lines"
        Ttbls_selected_txt = (
            str(agencies_folder) + "/" + str(Ttbls_selected_name) + ".txt"
        )

        files_to_delete_next_bus_loading_name = "files_to_delete_next_bus_loading"
        files_to_delete_next_bus_loading_json = (
            str(agencies_folder)
            + "/temp/"
            + str(files_to_delete_next_bus_loading_name)
            + ".json"
        )

        temp_folder = str(os.getenv("USERNAME")) + "_main_files"
        main_files_fld = os.path.join(str(agencies_folder) + "/" + str(temp_folder))
        main_files_csv = (
            str(agencies_folder) + "/" + str(temp_folder) + "/main_files.csv"
        )

        temp_folder = "temp/trip_id_assignement"
        folder_trip_id_assign = os.path.join(agencies_folder, temp_folder)

        ls_buses_done_name = "buses"
        ls_buses_done_csv = str(main_files_fld) + "/" + str(ls_buses_done_name) + ".csv"

        tempfolder = "temp/stop_times_perroute"
        temp_folder_Ttbls = os.path.join(agencies_folder, tempfolder)

        tempfolder = "temp/GTFSstops&segments_perroute"
        temp_folder_GTFSstops = os.path.join(agencies_folder, tempfolder)

        tempfolder = "temp/temp_roads_angls"
        temproadfldr = os.path.join(agencies_folder, tempfolder)

        tempfolderGTFSnm = "temp/temp_GTFSnomatch"
        temp_GTFSnm_folder = os.path.join(agencies_folder, tempfolderGTFSnm)

        tempfolder = "temp/temp_rect"
        temp_rect_folder = os.path.join(agencies_folder, tempfolder)

        tempfolder = "perdinst"
        perdist = os.path.join(temp_rect_folder, tempfolder)

        temp_folder = "temp/OSM_PTstops"
        OSMstops_temp_folder = os.path.join(agencies_folder, temp_folder)

        tempfolder = "temp/temp_OSM"
        temp_OSM_folder = os.path.join(agencies_folder, tempfolder)

        tempfolder = "temp/temp_GTFSpos"
        temp_GTFSpos_folder = os.path.join(agencies_folder, tempfolder)

        tempfolder = "temp/temp_OSM_forrouting"
        temp_OSM_for_routing = os.path.join(agencies_folder, tempfolder)

        GTFSnm_angledf_csv = str(outputspath) + "/GTFSnm_angl.csv"
        OSMwithGTFS_csv = str(outputspath) + "/OSMintersecGTFS.csv"
        dfnomatch_csv = str(outputspath) + "/OSMnomatch.csv"
        GTFSnm_rect_csv = str(outputspath) + "/GTFSnm_rect.csv"
        GTFSnmRCT_posdf_csv = str(outputspath) + "/GTFSnmRCT_NEWpos.csv"
        OSM4rout_file = str(outputspath) + "/OSM4routing.csv"

        GTFSnm_angledf = pd.DataFrame()
        OSMwithGTFS = pd.DataFrame()
        dfnomatch = pd.DataFrame()
        GTFSnm_rect = pd.DataFrame()
        GTFSnmRCT_posdf = pd.DataFrame()
        OSM4routing = pd.DataFrame()

        # condition if the plugin have aleady run at list ones
        if not os.path.exists(main_files_csv):
            transcript_main_files(
                main_files_fld,
                main_files_csv,
                OSM_ways_name,
                OSM_ways_gpkg,
                OSM_roads_name,
                OSM_roads_gpkg,
                OSM_roads_nameCSV,
                OSM_roads_csv,
                highway_speed_name,
                highway_speed_csv,
                bus_lanes_name,
                OSM_bus_lanes_gpkg,
                full_roads_name,
                full_roads_gpgk,
                Ttbls_selected_name,
                Ttbls_selected_txt,
                files_to_delete_next_bus_loading_name,
                files_to_delete_next_bus_loading_json,
            )

            os.makedirs(road_temp_folder)

            downloading_ways(extent, extent_quickosm, OSM_ways_gpkg)

            # Saving roads (only the lines of OSM file)
            Roads_layer_file = str(OSM_ways_gpkg) + "|layername=OSM_ways_lines"
            Roads_layer = QgsVectorLayer(Roads_layer_file, "Roads", "ogr")
            QgsVectorFileWriter.writeAsVectorFormat(
                Roads_layer, OSM_roads_gpkg, "UTF-8", Roads_layer.crs(), "GPKG"
            )
            QgsVectorFileWriter.writeAsVectorFormat(
                Roads_layer, OSM_roads_csv, "utf-8", driverName="CSV"
            )

            downloading_railway(extent, extent_quickosm, OSM_tramways_gpkg, "tram")

            # Saving rails (only the lines of OSM file)
            Rails_layer_file = (
                str(OSM_tramways_gpkg)
                + "|layername="
                + str(OSM_tramways_name)
                + "_lines"
            )
            Rials_layer = QgsVectorLayer(Rails_layer_file, OSM_tramways_name, "ogr")
            QgsVectorFileWriter.writeAsVectorFormat(
                Rials_layer, OSM_rails_gpkg, "UTF-8", Rials_layer.crs(), "GPKG"
            )

            downloading_railway(
                extent, extent_quickosm, OSM_Regtrainways_gpkg, "narrow_gauge"
            )
            # Saving Regtrain (only the lines of OSM file)
            Regtrain_layer_file = (
                str(OSM_Regtrainways_gpkg)
                + "|layername="
                + str(OSM_Regtrainways_name)
                + "_lines"
            )
            Regtrain_layer = QgsVectorLayer(
                Regtrain_layer_file, OSM_Regtrainways_name, "ogr"
            )
            QgsVectorFileWriter.writeAsVectorFormat(
                Regtrain_layer, OSM_Regtrain_gpkg, "UTF-8", Regtrain_layer.crs(), "GPKG"
            )

            downloading_railway(
                extent, extent_quickosm, OSM_funicularways_gpkg, "funicular"
            )
            funicular_layer_file = (
                str(OSM_funicularways_gpkg)
                + "|layername="
                + str(OSM_funicularways_name)
                + "_lines"
            )
            funicular_layer = QgsVectorLayer(
                funicular_layer_file, OSM_funicularways_name, "ogr"
            )
            QgsVectorFileWriter.writeAsVectorFormat(
                funicular_layer,
                OSM_funicular_gpkg,
                "UTF-8",
                funicular_layer.crs(),
                "GPKG",
            )

            highway_average_speed(OSM_roads_csv, highway_speed_csv)

            busroutes(
                bus_lanes_name, OSM_bus_lanes_gpkg, OSM_roads_gpkg, highway_speed_csv
            )

            full_city_roads(
                OSM_roads_gpkg,
                OSM_bus_lanes_gpkg,
                full_roads_gpgk,
                city_roads_name,
                highway_speed_csv,
            )

        if_not_make(temp_folder_Ttbls)
        if_not_make(temp_folder_GTFSstops)
        if_not_make(temproadfldr)
        if_not_make(temp_GTFSnm_folder)
        if_not_make(temp_rect_folder)
        if_not_make(perdist)
        if_not_make(OSMstops_temp_folder)
        if_not_make(temp_OSM_folder)
        if_not_make(temp_GTFSpos_folder)
        if_not_make(temp_OSM_for_routing)
        if_not_make(folder_trip_id_assign)

        if os.path.exists(GTFSnm_angledf_csv):
            GTFSnm_angledf = pd.read_csv(GTFSnm_angledf_csv)
        if os.path.exists(OSMwithGTFS_csv):
            OSMwithGTFS = pd.read_csv(OSMwithGTFS_csv)
        if os.path.exists(dfnomatch_csv):
            dfnomatch = pd.read_csv(dfnomatch_csv)
        if os.path.exists(GTFSnm_rect_csv):
            GTFSnm_rect = pd.read_csv(GTFSnm_rect_csv)
        if os.path.exists(GTFSnmRCT_posdf_csv):
            GTFSnmRCT_posdf = pd.read_csv(GTFSnmRCT_posdf_csv)
        if os.path.exists(OSM4rout_file):
            OSM4routing = pd.read_csv(OSM4rout_file)

        if os.path.exists(ls_buses_done_csv):
            ls_buses_df = pd.read_csv(ls_buses_done_csv)
            prev_ls_buses = [str(bus) for bus in list(ls_buses_df.trnsp_shrt_name)]
            del ls_buses_df

        if os.path.exists(files_to_delete_next_bus_loading_json):
            with open(files_to_delete_next_bus_loading_json, "r") as f:
                files_to_del = json.load(f)
        else:
            files_to_del = {"path": []}

        try:
            prev_ls_buses
        except NameError:
            prev_ls_buses = []

        ls_buses_selected = [item.text() for item in selected_items]

        print("the buses you have choosen are: " + str(ls_buses_selected))

        ls_buses = [bus for bus in ls_buses_selected if bus not in prev_ls_buses]

        prev_ls_buses = prev_ls_buses + ls_buses
        ls_buses_df = pd.DataFrame(prev_ls_buses).rename(columns={0: "trnsp_shrt_name"})
        if os.path.exists(ls_buses_done_csv):
            os.remove(ls_buses_done_csv)
        ls_buses_df.to_csv(ls_buses_done_csv, index=False)

        if not os.path.exists(Ttbls_plus_csv):
            Ttbls_plus(Ttlbs_txt, Ttbls_plus_csv, agencies_folder, trips_txt)

        print("Extracting the data of those transports")
        files_to_del = Selected_Ttbls(
            ls_buses, Ttbls_selected_txt, Ttbls_plus_csv, files_to_del
        )

        print(
            "the main Time Tables is ready, I start to create the dataframes for each single transport"
        )

        stops_times_plus = pd.read_csv(Ttbls_selected_txt)

        # create transport Times tables for each transport

        lsrts = stops_times_plus.route_id.unique()

        lslines = []

        if os.path.exists(lines_df_csv):
            lines_df = pd.read_csv(lines_df_csv, dtype={"route_short_name": str})
        else:
            lines_df = pd.DataFrame()

        lines_df_row_init = len(lines_df)

        sumTtbls = 0
        i_row = lines_df_row_init
        for rt in lsrts:
            line, nameline, Ttbl_file, rt_srt_nm, trnsprt_type, trnsp_shrt_name = (
                time_tables_perTransport(
                    rt, stops_times_plus, temp_folder_Ttbls, lslines
                )
            )
            sumTtbls = sumTtbls + len(line)
            lines_df.loc[i_row, "line_name"] = nameline
            lines_df.loc[i_row, "route_short_name"] = rt_srt_nm
            lines_df.loc[i_row, "GTFSstop_times"] = Ttbl_file
            lines_df.loc[i_row, "trnsprt_type"] = trnsprt_type
            lines_df.loc[i_row, "trnsp_shrt_name"] = trnsp_shrt_name
            lslines.append(nameline)
            i_row += 1

        print("The Time tables are ready")

        if len(stops_times_plus) == sumTtbls:
            print("all the lines are there")
        else:
            dif = len(stops_times_plus) - sumTtbls
            print(str(dif) + " scores are missing")

        print("prepariing the GTFSstops geopackages")

        # creating the a df for listing the files paths

        i_row = lines_df_row_init
        while i_row < len(lines_df):
            Ttbl_file = lines_df.loc[i_row, "GTFSstop_times"]
            line = lines_df.loc[i_row, "line_name"]
            shrt_name = lines_df.loc[i_row, "route_short_name"]
            GTFSstops, Ttbl_with_sequences_csv, files_to_del = (
                preapare_GTFSstops_by_transport(
                    stops_txt,
                    Ttbl_file,
                    line,
                    temp_folder_GTFSstops,
                    shrt_name,
                    temp_folder_Ttbls,
                    files_to_del,
                )
            )
            lines_df.loc[i_row, "GTFSstops&segments"] = GTFSstops
            lines_df.loc[i_row, "GTFSstop_times_with_seq"] = Ttbl_with_sequences_csv
            i_row = i_row + 1
        del i_row

        i_row = lines_df_row_init
        while i_row < len(lines_df):
            line = lines_df.loc[i_row, "line_name"]
            Ttbl_file = lines_df.loc[i_row, "GTFSstop_times"]
            GTFSstops_csv = lines_df.loc[i_row, "GTFSstops&segments"]
            line_trip_csv = (
                str(folder_trip_id_assign) + "/" + str(line) + "_trip_assignement.csv"
            )
            shape_assignement(GTFSstops_csv, Ttbl_file, line_trip_csv, trips_txt)
            lines_df.loc[i_row, "trip_assignement"] = line_trip_csv
            i_row += 1

        city_roads_layer = QgsVectorLayer(OSM_roads_gpkg, city_roads_name, "ogr")

        city_rails_layer = QgsVectorLayer(OSM_rails_gpkg, city_rails_name, "ogr")

        city_regtrain_layer = QgsVectorLayer(
            OSM_Regtrain_gpkg, city_Regtrain_name, "ogr"
        )

        city_funicular_layer = QgsVectorLayer(
            OSM_funicular_gpkg, city_funicular_name, "ogr"
        )

        print("... adding the angles to the GTFSstops")

        # create GTFSstops gpkg with angle of the nearest road

        i_row = lines_df_row_init
        while i_row < len(lines_df):

            line = lines_df.loc[i_row, "line_name"]
            GTFSstops_path = lines_df.loc[i_row, "GTFSstops&segments"]
            if lines_df.loc[i_row, "trnsprt_type"] == "Tram":
                GTFSstops_angle, GTFSnm_RD, GTFSnm_angCSV, spl_file = angles_tram(
                    city_rails_layer,
                    line,
                    GTFSstops_path,
                    temproadfldr,
                    temp_GTFSnm_folder,
                )
            elif lines_df.loc[i_row, "trnsprt_type"] == "RegRailServ":
                GTFSstops_angle, GTFSnm_RD, GTFSnm_angCSV, spl_file = angles_tram(
                    city_regtrain_layer,
                    line,
                    GTFSstops_path,
                    temproadfldr,
                    temp_GTFSnm_folder,
                )
            elif lines_df.loc[i_row, "trnsprt_type"] == "Funicular":
                GTFSstops_angle, GTFSnm_RD, GTFSnm_angCSV, spl_file = angles_tram(
                    city_funicular_layer,
                    line,
                    GTFSstops_path,
                    temproadfldr,
                    temp_GTFSnm_folder,
                )
            else:
                GTFSstops_angle, GTFSnm_RD, GTFSnm_angCSV, spl_file = angles_buses(
                    city_roads_layer,
                    line,
                    GTFSstops_path,
                    temproadfldr,
                    temp_GTFSnm_folder,
                )
            lines_df.loc[i_row, "GTFSnm_RD"] = GTFSnm_RD
            lines_df.loc[i_row, "GTFSstps_angle"] = GTFSstops_angle
            lines_df.loc[i_row, "GTFSnm_angCSV"] = GTFSnm_angCSV
            lines_df.loc[i_row, "Spl_roads"] = spl_file
            GTFSnm_angl_toconcat = pd.read_csv(GTFSnm_angCSV)
            GTFSnm_angledf = pd.concat(
                [GTFSnm_angledf, GTFSnm_angl_toconcat], ignore_index=True
            )
            i_row = i_row + 1

        files_to_del = if_remove(GTFSnm_angledf_csv, files_to_del)
        GTFSnm_angledf.to_csv(GTFSnm_angledf_csv, index=False)

        i_row = lines_df_row_init
        while i_row < len(lines_df):
            line = lines_df.loc[i_row, "line_name"]
            GTFSstops_angle = lines_df.loc[i_row, "GTFSstps_angle"]
            GTFSstops_angle_sidewalk_gpkg = (
                str(temproadfldr) + "/GTFS" + str(line) + "_anlge_sidewalk.gpkg"
            )
            GTFSstops_angle_OSMonROADline_gpkg = (
                str(temproadfldr) + "/GTFS" + str(line) + "_OSMonROADline.gpkg"
            )
            lines_df.loc[i_row, "GTFSstps_angle_sidewalk"] = (
                GTFSstops_angle_sidewalk_gpkg
            )
            lines_df.loc[i_row, "GTFSstps_angle_OSMonROADline"] = (
                GTFSstops_angle_OSMonROADline_gpkg
            )
            angle_onRD_sidewalk(
                GTFSstops_angle,
                GTFSstops_angle_sidewalk_gpkg,
                GTFSstops_angle_OSMonROADline_gpkg,
                agency_txt,
            )
            i_row = i_row + 1

        print("Creating vector layers to join to the OSM stops")

        buses_long = 0.00020
        tram_long = 0.00080
        road_average_width = 0.00008

        i_row = lines_df_row_init
        while i_row < len(lines_df):

            GTFSstops_angle_sidewalk_gpkg = lines_df.loc[
                i_row, "GTFSstps_angle_sidewalk"
            ]
            line = lines_df.loc[i_row, "line_name"]
            trnsprt_type = lines_df.loc[i_row, "trnsprt_type"]
            GTFSstps_rect_sidewalk_csv = (
                str(temp_rect_folder) + "/GTFSangl_sidewalk_" + str(line) + ".csv"
            )
            GTFSstps_rect_sidewalk_gpkg = (
                str(temp_rect_folder) + "/rects_sidewalk_" + str(line) + ".gpkg"
            )
            GTFSstops_angle_sidewalk_layer = QgsVectorLayer(
                GTFSstops_angle_sidewalk_gpkg,
                "GTFS" + str(line) + "_anlge_sidewalk",
                "ogr",
            )
            ls_GTFSstps_rect = []
            if not GTFSstops_angle_sidewalk_layer.featureCount() == 0:
                files_to_del = rectangles_sidewalk(
                    GTFSstops_angle_sidewalk_gpkg,
                    buses_long,
                    tram_long,
                    line,
                    GTFSstps_rect_sidewalk_gpkg,
                    GTFSstps_rect_sidewalk_csv,
                    trnsprt_type,
                    files_to_del,
                )
                lines_df.loc[i_row, "GTFSstps_rect_sidewalk_gpkg"] = (
                    GTFSstps_rect_sidewalk_gpkg
                )
                lines_df.loc[i_row, "GTFSstps_rect_sidewalk_csv"] = (
                    GTFSstps_rect_sidewalk_csv
                )
                ls_GTFSstps_rect.append(GTFSstps_rect_sidewalk_gpkg)

            GTFSstops_path_OSMonROADline = lines_df.loc[
                i_row, "GTFSstps_angle_OSMonROADline"
            ]
            GTFSstps_rect_OSMonROADline_gpkg = (
                str(temp_rect_folder) + "/rects_OSMonROADline_" + str(line) + ".gpkg"
            )
            GTFSstops_angle_OSMonROADline_layer = QgsVectorLayer(
                GTFSstops_path_OSMonROADline,
                "GTFS" + str(line) + "_OSMonROADline",
                "ogr",
            )
            if not GTFSstops_angle_OSMonROADline_layer.featureCount() == 0:
                rectangles_OSMonROADline(
                    GTFSstops_path_OSMonROADline,
                    buses_long,
                    tram_long,
                    road_average_width,
                    line,
                    GTFSstps_rect_OSMonROADline_gpkg,
                    trnsprt_type,
                )
                ls_GTFSstps_rect.append(GTFSstps_rect_OSMonROADline_gpkg)

            GTFSstps_rect_gpkg = str(temp_rect_folder) + "/rects_" + str(line) + ".gpkg"
            lines_df.loc[i_row, "GTFSstps_rect"] = GTFSstps_rect_gpkg
            if ls_GTFSstps_rect and (
                not 29 in ls_agency or not 344 in ls_agency or not 764 in ls_agency
            ):
                params = {
                    "LAYERS": ls_GTFSstps_rect,
                    "CRS": QgsCoordinateReferenceSystem("EPSG:4326"),
                    "OUTPUT": GTFSstps_rect_gpkg,
                }
                processing.run("native:mergevectorlayers", params)
            else:
                layerType = "Polygon"
                crs = "EPSG:4326"
                emptyLayer = QgsVectorLayer(
                    f"{layerType}?crs={crs}", "New Empty Layer", "memory"
                )
                fields = QgsFields()
                fields.append(QgsField("fid", QVariant.Int))
                fields.append(QgsField("line_name", QVariant.String))
                emptyLayer.startEditing()
                emptyLayer.dataProvider().addAttributes(fields.toList())
                emptyLayer.updateFields()
                emptyLayer.commitChanges()
                QgsVectorFileWriter.writeAsVectorFormat(
                    emptyLayer, GTFSstps_rect_gpkg, "UTF-8", emptyLayer.crs(), "GPKG"
                )

            i_row = i_row + 1

        i_row = lines_df_row_init

        while i_row < len(lines_df):
            line = lines_df.loc[i_row, "line_name"]
            shrt_name = lines_df.loc[i_row, "route_short_name"]
            trnsprt_type = lines_df.loc[i_row, "trnsprt_type"]

            OSM_PTstp_rel_name = "PT_stops_rel_" + str(line)
            OSM_PTstp_rel_gpkg = (
                str(OSMstops_temp_folder) + "/" + str(OSM_PTstp_rel_name) + ".gpkg"
            )
            OSM_PTstp_name = "PT_stop_position_" + str(line)
            OSM_PTstp_gpkg = (
                str(OSMstops_temp_folder) + "/" + str(OSM_PTstp_name) + ".gpkg"
            )
            lines_df.loc[i_row, "OSM_PTstp"] = OSM_PTstp_gpkg
            OSM_PTstps_dwnld(
                extent,
                extent_quickosm,
                OSM_PTstp_rel_gpkg,
                OSM_PTstp_gpkg,
                shrt_name,
                OSM_PTstp_rel_name,
                OSM_PTstp_name,
                trnsprt_type,
            )
            i_row += 1

        print("joining OSM and GTFS")

        i_row = lines_df_row_init
        while i_row < len(lines_df):
            line = lines_df.loc[i_row, "line_name"]
            rect = lines_df.loc[i_row, "GTFSstps_rect"]
            OSM_PTstp_gpkg = lines_df.loc[i_row, "OSM_PTstp"]
            intersect, match, OSMjnGTFS, OSMnomatch = OSMintersecGTFS(
                rect, OSM_PTstp_gpkg, temp_OSM_folder, line
            )
            lines_df.loc[i_row, "OSMintersecGTFS"] = OSMjnGTFS
            lines_df.loc[i_row, "OSMnomatch"] = OSMnomatch

            OSMwithGTFS = pd.concat([OSMwithGTFS, intersect], ignore_index=True)
            dfnomatch = pd.concat([dfnomatch, match], ignore_index=True)

            i_row = i_row + 1

        files_to_del = if_remove(OSMwithGTFS_csv, files_to_del)
        OSMwithGTFS.to_csv(OSMwithGTFS_csv, index=False)
        files_to_del = if_remove(dfnomatch_csv, files_to_del)
        dfnomatch.to_csv(dfnomatch_csv, index=False)

        # create list of GTFS rectangls that don't match with any OSM
        i_row = lines_df_row_init
        while i_row < len(lines_df):
            OSMjnGTFS = pd.read_csv(lines_df.loc[i_row, "OSMintersecGTFS"])
            GTFSstops = pd.read_csv(lines_df.loc[i_row, "GTFSstops&segments"])
            GTFSnm_RD = pd.read_csv(lines_df.loc[i_row, "GTFSnm_angCSV"])
            GTFSnmRCT_csv = (
                str(temp_GTFSnm_folder)
                + "/GTFSnmRCT_"
                + str(lines_df.loc[i_row, "line_name"])
                + ".csv"
            )
            if not OSMjnGTFS.empty:
                lsGTFSjoined = OSMjnGTFS.GTFS_stop_id.unique()
                GTFSstops = GTFSstops[~GTFSstops.stop_id.isin(lsGTFSjoined)]

            if not GTFSnm_RD.empty:
                lsGTFSnmRD = GTFSnm_RD.stop_id.unique()
                GTFSstops = GTFSstops[~GTFSstops.stop_id.isin(lsGTFSnmRD)]

            GTFSnmRCT = GTFSstops
            GTFSnmRCT.to_csv(GTFSnmRCT_csv, index=False)
            lines_df.loc[i_row, "GTFSnmRCT"] = GTFSnmRCT_csv
            GTFSnm_rect = pd.concat([GTFSnm_rect, GTFSnmRCT], ignore_index=True)

            i_row += 1

        if os.path.exists(GTFSnm_rect_csv):
            os.remove(GTFSnm_rect_csv)
        GTFSnm_rect.to_csv(GTFSnm_rect_csv, index=False)

        i_row = lines_df_row_init
        while i_row < len(lines_df):
            trnsprt_type = lines_df.loc[i_row, "trnsprt_type"]
            line_name = lines_df.loc[i_row, "line_name"]
            GTFSnmRCT_csv = lines_df.loc[i_row, "GTFSnmRCT"]
            splt_roads = lines_df.loc[i_row, "Spl_roads"]
            test = pd.read_csv(GTFSnmRCT_csv)
            if not test.empty:
                NEWpos_file_nmRCT, files_to_del = stp_posGTFSnm_rect(
                    GTFSnmRCT_csv,
                    line_name,
                    splt_roads,
                    temp_GTFSpos_folder,
                    buses_long,
                    tram_long,
                    trnsprt_type,
                    agency_txt,
                    files_to_del,
                )
            else:
                NEWpos_file_nmRCT = (
                    str(temp_GTFSpos_folder)
                    + "/GTFSnmRCT_pos_"
                    + str(line_name)
                    + ".csv"
                )

            lines_df.loc[i_row, "GTFSnmRCT_newOSMpos"] = NEWpos_file_nmRCT
            posdf = pd.read_csv(NEWpos_file_nmRCT)
            GTFSnmRCT_posdf = pd.concat([GTFSnmRCT_posdf, posdf], ignore_index=True)
            i_row += 1

        files_to_del = if_remove(GTFSnmRCT_posdf_csv, files_to_del)
        GTFSnmRCT_posdf.to_csv(GTFSnmRCT_posdf_csv, index=False)

        files_to_del_str = json.dumps(files_to_del, indent=2)
        with open(files_to_delete_next_bus_loading_json, "w") as f:
            f.write(files_to_del_str)
        if files_to_del["path"]:
            print("the files will be deleted only restarting QGIS")
            print('RESTART QGIS and click again the "Update Transport numbers" button')

        i_row = lines_df_row_init
        while i_row < len(lines_df):
            newOSMpos = lines_df.loc[i_row, "GTFSnmRCT_newOSMpos"]
            GTFSnomatch_RD = lines_df.loc[i_row, "GTFSnm_angCSV"]
            OSMintersectGTFS = lines_df.loc[i_row, "OSMintersecGTFS"]
            GTFSstps_seg = lines_df.loc[i_row, "GTFSstops&segments"]
            line = lines_df.loc[i_row, "line_name"]
            OSMstops_forrouting, files_to_del = joinNEWandValidOSM(
                newOSMpos,
                GTFSnomatch_RD,
                OSMintersectGTFS,
                GTFSstps_seg,
                temp_OSM_for_routing,
                line,
                stops_txt,
                files_to_del,
            )
            lines_df.loc[i_row, "OSM4routing"] = OSMstops_forrouting
            OSM4r_toconcat = pd.read_csv(OSMstops_forrouting)
            OSM4routing = pd.concat([OSM4routing, OSM4r_toconcat], ignore_index=True)
            i_row += 1

        if os.path.exists(OSM4rout_file):
            os.remove(OSM4rout_file)
        OSM4routing.to_csv(OSM4rout_file, index=False)

        # publishing the back ground for better read of the data
        if not QgsProject.instance().mapLayersByName("SWISSIMAGE 10 cm"):
            uri = "contextualWMSLegend=0&crs=EPSG:4326&dpiMode=7&featureCount=10&format=image/jpeg&layers=ch.swisstopo.swissimage&styles=default&tilePixelRatio=0&url=https://wms.geo.admin.ch/"
            CHimage_layer = QgsRasterLayer(uri, "SWISSIMAGE 10 cm", "wms")
            QgsProject.instance().addMapLayer(CHimage_layer)

        if not QgsProject.instance().mapLayersByName("OSM Standard"):
            uri = "type=xyz&zmin=0&zmax=19&url=http://tile.openstreetmap.org/{z}/{x}/{y}.png"
            OSMmap_layer = QgsRasterLayer(uri, "OSM Standard", "wms")
            QgsProject.instance().addMapLayer(OSMmap_layer)

        if not QgsProject.instance().mapLayersByName(city_roads_name):
            city_roads_layer = QgsVectorLayer(OSM_roads_gpkg, city_roads_name, "ogr")
            QgsProject.instance().addMapLayer(city_roads_layer)

        if_display(OSM_rails_gpkg, city_rails_name)

        if_display(OSM_Regtrain_gpkg, city_Regtrain_name)

        if_display(OSM_funicular_gpkg, city_funicular_name)

        # publishing the trips on the canvas
        ls_buses_todisp = [str(bus) for bus in ls_buses_selected]
        ls_buses_select_df = pd.DataFrame(ls_buses_todisp).rename(
            columns={0: "trnsp_shrt_name"}
        )
        ls_buses_select_df = ls_buses_select_df.astype({"trnsp_shrt_name": "str"})
        ls_buses_select_df = ls_buses_select_df.merge(
            lines_df, how="left", on="trnsp_shrt_name"
        )
        ls_trnsprt_todisplay = list(ls_buses_select_df.line_name.unique())
        ls_files = os.listdir(temp_OSM_for_routing)
        ls_gpkg = [file for file in ls_files if ".gpkg" in file]

        for trnsprt in ls_trnsprt_todisplay:
            to_display = [str(gpkg) for gpkg in ls_gpkg if trnsprt in gpkg]
            for layer in to_display:
                if not QgsProject.instance().mapLayersByName(str(layer[:-5])):
                    OSM_trip4rout_gpkg = str(temp_OSM_for_routing) + "/" + str(layer)
                    OSM_trip4rout_layer = QgsVectorLayer(
                        OSM_trip4rout_gpkg, str(layer[:-5]), "ogr"
                    )
                    QgsProject.instance().addMapLayer(OSM_trip4rout_layer)

        # saving the lines df
        if os.path.exists(lines_df_csv):
            os.remove(lines_df_csv)
        lines_df.to_csv(lines_df_csv, index=False)

        #  >>>>>>>>>>>>     XXXXXXXXXXXXXXXXXXXX     <<<<<<<<<<<
        #  >>>  !!! ---- OSM_PT_rounting functions ---- !!! <<<<
        #  >>>>>>>>>>>>     XXXXXXXXXXXXXXXXXXXX     <<<<<<<<<<<

        self.stopsnmRDlistWidget.clear()  # Clear existing items

        folder_OSM = "OSM_data"
        road_temp_folder = os.path.join(agencies_folder, folder_OSM)

        temp_folder = "zoom_nmRD"
        nmRD_temp_folder = os.path.join(agencies_folder, temp_folder)

        full_roads_name = "full_city_roads"
        full_roads_gpgk = str(road_temp_folder) + "/" + str(full_roads_name) + ".gpkg"

        OSMallroad_name = "OSMallroad"
        OSMallroad_gpkg = os.path.join(nmRD_temp_folder, str(OSMallroad_name) + ".gpkg")

        tram_rails_name = "OSM_tram"
        tram_rails_gpgk = str(road_temp_folder) + "/" + str(tram_rails_name) + ".gpkg"

        OSM_Regtrain_name = "OSM_Regtrain"
        OSM_Regtrain_gpkg = (
            str(road_temp_folder) + "/" + str(OSM_Regtrain_name) + ".gpkg"
        )

        OSM_funicular_name = "OSM_funicular"
        OSM_funicular_gpkg = (
            str(road_temp_folder) + "/" + str(OSM_funicular_name) + ".gpkg"
        )

        if not os.path.exists(nmRD_temp_folder):
            os.mkdir(nmRD_temp_folder)

        if not os.path.exists(OSMallroad_gpkg):
            ls_roads = []
            if os.path.exists(full_roads_gpgk):
                ls_roads.append(full_roads_gpgk)
            if os.path.exists(tram_rails_gpgk):
                ls_roads.append(tram_rails_gpgk)
            if os.path.exists(OSM_Regtrain_gpkg):
                ls_roads.append(OSM_Regtrain_gpkg)
            if os.path.exists(OSM_funicular_gpkg):
                ls_roads.append(OSM_funicular_gpkg)
            params = {
                "LAYERS": ls_roads,
                "CRS": QgsCoordinateReferenceSystem("EPSG:4326"),
                "OUTPUT": OSMallroad_gpkg,
            }
            processing.run("native:mergevectorlayers", params)

        tempfolder = "temp/temp_OSM_forrouting"
        temp_OSM_for_routing = os.path.join(agencies_folder, tempfolder)

        allstops_name = "ALLstops"
        allstops_gpkg = os.path.join(nmRD_temp_folder, str(allstops_name) + ".gpkg")
        allstops_csv = os.path.join(nmRD_temp_folder, str(allstops_name) + ".csv")

        nmRD_stops_name = "nmRD_stops"
        nmRD_stops_csv = os.path.join(nmRD_temp_folder, str(nmRD_stops_name) + ".csv")

        ls_files = os.listdir(temp_OSM_for_routing)
        ls_to_check = [file for file in ls_files if ".gpkg" in file]

        allstops_to_check = pd.DataFrame()
        for to_check in ls_to_check:
            to_check_name = to_check[:-5]
            to_check_gpkg = os.path.join(temp_OSM_for_routing, to_check)
            to_check_csv = os.path.join(nmRD_temp_folder, str(to_check_name) + ".csv")
            to_check_layer = QgsVectorLayer(to_check_gpkg, to_check_name, "ogr")
            ls_fields_name_to_remove = ["lon", "lat"]

            for field_name in ls_fields_name_to_remove:
                field_index = to_check_layer.fields().indexFromName(field_name)
                if field_index != -1:
                    to_check_layer.startEditing()
                    to_check_layer.deleteAttribute(field_index)
                    to_check_layer.commitChanges()
                else:
                    print(f"Field '{field_name}' not found.")

            pr = to_check_layer.dataProvider()
            pr.addAttributes(
                [QgsField("lon", QVariant.Double), QgsField("lat", QVariant.Double)]
            )
            to_check_layer.updateFields()
            to_check_layer.commitChanges()

            expression2 = QgsExpression("$x")
            expression3 = QgsExpression("$y")

            context = QgsExpressionContext()
            context.appendScopes(
                QgsExpressionContextUtils.globalProjectLayerScopes(to_check_layer)
            )

            with edit(to_check_layer):
                for f in to_check_layer.getFeatures():
                    context.setFeature(f)
                    f["lon"] = expression2.evaluate(context)
                    f["lat"] = expression3.evaluate(context)
                    to_check_layer.updateFeature(f)

            if_remove_single_file(to_check_csv)
            QgsVectorFileWriter.writeAsVectorFormat(
                to_check_layer, to_check_csv, "utf-8", driverName="CSV"
            )
            df_to_check = pd.read_csv(
                to_check_csv, dtype={"trip": int, "pos": int, "stop_id": str}
            )
            if not df_to_check.empty:
                allstops_to_check = pd.concat(
                    [allstops_to_check, df_to_check], ignore_index=True
                )

        allstops_to_check.to_csv(allstops_csv, index=False)

        allstops_path = r"file:///{}?crs={}&delimiter={}&xField={}&yField={}".format(
            allstops_csv, "epsg:4326", ",", "lon", "lat"
        )
        allstops_layer = QgsVectorLayer(allstops_path, allstops_name, "delimitedtext")

        param = {
            "INPUT": allstops_layer,
            "REFERENCE": OSMallroad_gpkg,
            "DISTANCE": 0.0000001,
            "METHOD": 0,
        }
        processing.run("native:selectwithindistance", param)

        allstops_layer.invertSelection()

        QgsVectorFileWriter.writeAsVectorFormat(
            allstops_layer, nmRD_stops_csv, "utf-8", driverName="CSV", onlySelected=True
        )
        # buffer on those stops
        # clip roads/rail

        # feature by feature nearest distance new xy
        to_check = pd.read_csv(
            nmRD_stops_csv, dtype={"trip": int, "pos": int, "stop_id": str}
        )

        if not to_check.empty:
            i_row = 0
            while i_row < len(to_check):
                to_check.loc[i_row, "seq_stpID"] = (
                    str(to_check.loc[i_row, "line_name"])
                    + "_trip"
                    + str(to_check.loc[i_row, "trip"])
                    + "_pos"
                    + str(to_check.loc[i_row, "pos"])
                )
                i_row += 1

            ls_stop_to_display = to_check.seq_stpID.unique()

            for stop_to_disp in ls_stop_to_display:
                self.stopsnmRDlistWidget.addItem(QListWidgetItem(str(stop_to_disp)))
            if_remove_single_file(nmRD_stops_csv)
            to_check.to_csv(nmRD_stops_csv)
        else:
            self.stopsnmRDlistWidget.addItem(
                QListWidgetItem(
                    str(
                        "All the stops are on one of the networks (roads'one or rails'one)"
                    )
                )
            )

        self.toolBox.setCurrentIndex(2)

        print(f"Done!{datetime.datetime.now()}")

    def __ZoomStop(self):

        gtfs_folder_path = self.mGtfsFolderWidget.filePath()

        outputspath = "to define"  # to define
        if not os.path.exists(outputspath):
            os.makedirs(outputspath)

        selected_agencies = self.listAgenciesWidget.selectedItems()

        ls_agencies_selected = [item.text() for item in selected_agencies]

        agen_folder = "agen"
        agencies_num = [agen.split(" - ")[0] for agen in ls_agencies_selected]
        for agen in agencies_num:
            agen_folder = str(agen_folder) + "_" + str(agen)

        agencies_folder = os.path.join(gtfs_folder_path, agen_folder)

        temp_folder = "zoom_nmRD"
        nmRD_temp_folder = os.path.join(agencies_folder, temp_folder)
        nmRD_stops_name = "nmRD_stops"

        nmRD_stops_csv = os.path.join(nmRD_temp_folder, str(nmRD_stops_name) + ".csv")

        to_check = pd.read_csv(nmRD_stops_csv, index_col="seq_stpID")
        selected_item = self.stopsnmRDlistWidget.currentItem().text()
        print(selected_item)

        print(to_check.at[selected_item, "lat"])

        latitude = float(to_check.at[selected_item, "lat"])
        longitude = float(to_check.at[selected_item, "lon"])
        target_point = QgsPointXY(longitude, latitude)

        canvas = self.iface.mapCanvas()

        canvas.setCenter(target_point)

        canvas.zoomScale(50)

        canvas.refresh()

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
